[package]
name = "read2umi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdf5 = "0.8.1"
itertools = "0.13.0"
arrow = "53.3.0"
parquet = "53.3.0"
